"""empty message

Revision ID: 8830024088ef
Revises: 7d0f98541145
Create Date: 2019-12-15 19:33:18.797945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8830024088ef'
down_revision = '7d0f98541145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passwords')
    # ### end Alembic commands ###
